# Generated by Django 3.2.7 on 2022-11-18 01:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2347035678987', max_length=30, region=None, verbose_name='Phone Number'),
        ),
    ]
