# Generated by Django 3.2.7 on 2022-11-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plot Area(m^2)'),
        ),
    ]
